name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Subir archivos mediante SFTP
      - name: Deploy to Hostinger
        env:
          HOST: ${{ secrets.HOSTINGER_HOST }}
          USER: ${{ secrets.HOSTINGER_USER }}
          PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u "$USER,$PASSWORD" "$HOST" <<EOF
          set ssl:verify-certificate no
          mirror -R --delete --only-newer out/ /new/
          quit
          EOF
